export default {
	SET_SUBSTITUTES: 'substitutes/SET_SUBSTITUTES',
	SET_SUBSTITUTES_OPTIONS: 'substitutes/SET_SUBSTITUTES_OPTIONS',
	UPDATE_ORDER_INFO: 'substitutes/UPDATE_ORDER_INFO',
	SET_ORDER_SUBSTITUTE_VALUE: 'substitutes/SET_ORDER_SUBSTITUTE_VALUE'
};
